import type {Metadata} from "next";
import {Analytics} from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import {Open_Sans, Roboto} from "next/font/google";
import "./globals.css";
import css from './layout.module.css';
import {NavLink} from "@/components/NavLink";

const roboto = Roboto({
    weight: '300',
    subsets: ['latin'],
    variable: '--font-roboto'
})
const openSans = Open_Sans({
    weight: '300',
    subsets: ["latin"],
    variable: "--font-open-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${css.application}`}>
        <header className={`${openSans.className} ${css.header}`}>
            <h1>Utgaard</h1>
        </header>
        <main className={`${roboto.className} ${css.main}`}>
            <menu className={css.menu}>
                <li><NavLink href="/pages">Pages</NavLink></li>
                <li><NavLink href="/repos">Repos</NavLink></li>
                <li><NavLink href="/about">About</NavLink></li>
            </menu>
            <div className={css.content}>
                {children}
            </div>
        </main>
        <footer className={`${openSans.className} ${css.footer}`}>
            <h1>Utgaard</h1>
        </footer>
        <Analytics />
        <SpeedInsights />
        </body>
        </html>
    );
}
